# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
---
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "skip-changelog"
    schedule:
      interval: "monthly"
