tasks:
  - init: mvn clean verify

vscode:
  extensions:
    - bierner.markdown-preview-github-styles
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
